import type { BackupManifest, FiberSnapshot, RecoveryArchive, RecoveryEnvelope } from "./types";
import { decryptBytes, encryptBytes, sha256Hex } from "./crypto";
import { base64ToBytes, bytesToBase64, text, utf8 } from "./encoding";

const MAX_CIPHERTEXT_BYTES = 256 * 1024 * 1024;
export const MAX_ARCHIVE_JSON_BYTES = 350 * 1024 * 1024;

function publicAad(manifest: BackupManifest): Uint8Array {
  // Build a fixed-order object so JSON property order from an imported file is irrelevant.
  return utf8(JSON.stringify({
    format: manifest.format,
    formatVersion: manifest.formatVersion,
    createdAt: manifest.createdAt,
    cipher: manifest.payload.cipher,
    kdf: manifest.payload.kdf,
    iterations: manifest.payload.iterations,
    aadVersion: manifest.payload.aadVersion
  }));
}

function assertSnapshot(snapshot: FiberSnapshot): void {
  if (!snapshot || typeof snapshot !== "object") throw new Error("Archive recovery snapshot is missing.");
  if (!snapshot.nodeId || !snapshot.fiberVersion || !snapshot.networkIdentity || !snapshot.adapter) {
    throw new Error("Archive recovery snapshot is incomplete.");
  }
  if (!["testnet", "mainnet", "unknown"].includes(snapshot.network)) {
    throw new Error("Archive recovery snapshot has an invalid network name.");
  }
  if (Number.isNaN(Date.parse(snapshot.capturedAt))) {
    throw new Error("Archive recovery snapshot has an invalid capture timestamp.");
  }
  if (!Array.isArray(snapshot.channels) || !Array.isArray(snapshot.payments) || !Array.isArray(snapshot.invoices)) {
    throw new Error("Archive recovery snapshot record lists are invalid.");
  }
  const coverage = [snapshot.capabilities?.channels, snapshot.capabilities?.payments, snapshot.capabilities?.invoices];
  if (coverage.some((value) => !["full", "metadata", "unavailable"].includes(value ?? ""))) {
    throw new Error("Archive recovery snapshot capabilities are invalid.");
  }

  const assertUniqueRecords = (records: Array<{ id: string }>, label: string) => {
    if (records.some((record) => !record || typeof record.id !== "string" || record.id.length === 0)) {
      throw new Error(`Archive recovery snapshot contains an invalid ${label} identifier.`);
    }
    if (new Set(records.map((record) => record.id)).size !== records.length) {
      throw new Error(`Archive recovery snapshot contains duplicate ${label} identifiers.`);
    }
  };
  assertUniqueRecords(snapshot.channels, "channel");
  assertUniqueRecords(snapshot.payments, "payment");
  assertUniqueRecords(snapshot.invoices, "invoice");
  if (snapshot.channels.some((record) => typeof record.state !== "string") ||
      snapshot.payments.some((record) => typeof record.status !== "string") ||
      snapshot.invoices.some((record) => typeof record.status !== "string")) {
    throw new Error("Archive recovery snapshot contains invalid record state/status values.");
  }
}

export async function createArchive(
  snapshot: FiberSnapshot,
  nativeBackup: Uint8Array,
  password: string
): Promise<RecoveryArchive> {
  assertSnapshot(snapshot);
  const createdAt = new Date().toISOString();

  // A first immutable header is enough to bind all security-relevant public parameters.
  // Salt/IV are generated by encryptBytes and are self-protecting: tampering prevents decryption.
  const manifestBase: BackupManifest = {
    format: "fiber-continuity",
    formatVersion: 2,
    createdAt,
    payload: {
      cipher: "AES-GCM-256",
      kdf: "PBKDF2-SHA256",
      iterations: 310_000,
      salt: "",
      iv: "",
      aadVersion: 1,
      ciphertextDigest: ""
    }
  };

  const envelope: RecoveryEnvelope = {
    schemaVersion: 1,
    snapshot,
    nativeBackup: bytesToBase64(nativeBackup)
  };
  const plain = utf8(JSON.stringify(envelope));
  const encrypted = await encryptBytes(plain, password, publicAad(manifestBase), manifestBase.payload.iterations);

  const manifest: BackupManifest = {
    ...manifestBase,
    payload: {
      ...manifestBase.payload,
      iterations: encrypted.iterations,
      salt: bytesToBase64(encrypted.salt),
      iv: bytesToBase64(encrypted.iv),
      ciphertextDigest: await sha256Hex(encrypted.ciphertext)
    }
  };

  return {
    manifest,
    ciphertext: bytesToBase64(encrypted.ciphertext)
  };
}

export async function validateArchive(archive: RecoveryArchive): Promise<void> {
  if (!archive?.manifest || typeof archive.ciphertext !== "string") {
    throw new Error("Not a FiberContinuity archive.");
  }
  const { manifest } = archive;
  if (manifest.format !== "fiber-continuity") throw new Error("Not a FiberContinuity archive.");
  if (manifest.formatVersion !== 2) {
    if ((manifest as { formatVersion?: number }).formatVersion === 1) {
      throw new Error("Legacy FiberContinuity v1 archives are intentionally blocked because their metadata was not authenticated. Recreate the backup with v2.");
    }
    throw new Error("Unsupported FiberContinuity archive format version.");
  }
  if (Number.isNaN(Date.parse(manifest.createdAt))) {
    throw new Error("Recovery archive has an invalid creation timestamp.");
  }
  if (manifest.payload.cipher !== "AES-GCM-256" || manifest.payload.kdf !== "PBKDF2-SHA256" || manifest.payload.aadVersion !== 1) {
    throw new Error("Unsupported FiberContinuity cryptographic parameters.");
  }
  if (!/^[0-9a-f]{64}$/i.test(manifest.payload.ciphertextDigest)) {
    throw new Error("Recovery archive has an invalid ciphertext digest.");
  }
  if (!Number.isInteger(manifest.payload.iterations) || manifest.payload.iterations < 100_000 || manifest.payload.iterations > 2_000_000) {
    throw new Error("Unsupported FiberContinuity PBKDF2 iteration count.");
  }
  if (archive.ciphertext.length > Math.ceil(MAX_CIPHERTEXT_BYTES * 4 / 3) + 8) {
    throw new Error("Recovery archive exceeds the supported size limit.");
  }

  const bytes = base64ToBytes(archive.ciphertext);
  if (bytes.length > MAX_CIPHERTEXT_BYTES) throw new Error("Recovery archive exceeds the supported size limit.");
  const digest = await sha256Hex(bytes);
  if (digest !== manifest.payload.ciphertextDigest) {
    throw new Error("Encrypted payload corruption check failed.");
  }
}

export async function decryptArchive(
  archive: RecoveryArchive,
  password: string
): Promise<{ snapshot: FiberSnapshot; nativeBackup: Uint8Array }> {
  await validateArchive(archive);
  const plain = await decryptBytes(
    base64ToBytes(archive.ciphertext),
    password,
    archive.manifest.payload.salt,
    archive.manifest.payload.iv,
    archive.manifest.payload.iterations,
    publicAad(archive.manifest)
  );

  let envelope: RecoveryEnvelope;
  try {
    envelope = JSON.parse(text(plain)) as RecoveryEnvelope;
  } catch {
    throw new Error("Authenticated recovery payload is not valid JSON.");
  }
  if (envelope.schemaVersion !== 1 || typeof envelope.nativeBackup !== "string") {
    throw new Error("Unsupported authenticated recovery payload schema.");
  }
  assertSnapshot(envelope.snapshot);
  return {
    snapshot: envelope.snapshot,
    nativeBackup: base64ToBytes(envelope.nativeBackup)
  };
}

export function parseArchive(json: string): RecoveryArchive {
  if (utf8(json).byteLength > MAX_ARCHIVE_JSON_BYTES) {
    throw new Error("Recovery archive file is too large.");
  }
  let value: unknown;
  try {
    value = JSON.parse(json);
  } catch {
    throw new Error("Recovery archive is not valid JSON.");
  }
  const archive = value as Partial<RecoveryArchive> & { manifest?: { format?: unknown } };
  if (archive?.manifest?.format !== "fiber-continuity" || typeof archive.ciphertext !== "string") {
    throw new Error("Not a FiberContinuity archive.");
  }
  return archive as RecoveryArchive;
}
